### ISSUE TITLE
Add a reference to the ReadMe in the Release template 

### ISSUE THREAD

**Issue by IvanDomashchenko** [SitecoreSupport/ReleaseDaemon#7]
Please add a reference to the ReadMe.md file in the 'Description' section of the 'Release' template, for example: 

```
#### Description
// TODO Add description
Please refer the [ReadMe](../..) for more details.
```

The ReadMe can contain detailed explanation of the patch and issue which it solves. 
SO now, to provider a customer with full information about patch, an engineer has to send 2 links (to readme and release) or to duplicate the same information in the Release.

**Comment by AlenPelin** [comment]
> an engineer has to send 2 links (to readme and release) or to duplicate the same information in the Release.
Readme section is somewhat optional in general, the only purpose of this file to help Sitecore engineer to understand what it is really fast i.e. without opening reference ticket. Duplicating information in release details is not recommended because release text must be as short and clear as possible.

**Comment by AlenPelin** [comment]
It was decided to completely remove the **description** section from master/readme.md
